version: '3'

volumes:
  postgres_data:  

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sunar2024
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  reverse-proxy:
    image: traefik:v2.10
    command: 
      --api.insecure=true 
      --providers.docker
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443
      --certificatesresolvers.letresolver.acme.email=upper.desenvolvimento@gmail.com
      --certificatesresolvers.letresolver.acme.storage=acme.json
      --certificatesresolvers.letresolver.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks: 
  default: 
    external: 
      name: infra-db

# docker network create infra-db